language: node_js
node_js: '12'
cache: yarn

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      install: npm install
      script: npm run lint
    - stage: test
      install: npm install
      script: npm run test
